apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: stress-deployment-balanced
  name: stress-deployment-balanced
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stress-balanced
  template:
    metadata:
      labels:
        app: stress-balanced
    spec:
      containers:
      - name: stress-balanced
        image: polinux/stress
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "900", "--timeout", "1000"]
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: stress-balanced